### ISSUE TITLE
CXX_STANDARD 14 Problems in Relation to esp-idf-v5.1.1

### ISSUE THREAD

**Issue by franz-ms-muc** [Open-Agriculture/AgIsoStack-plus-plus#357] opened 2023-11-25 09:54 UTC
**Describe the bug**
CXX_STANDARD 14 Problems in Relation to esp-idf-v5.1.1

**Supporting Documentation**
https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/AgIsoStack-plus-plus-sample/tree/cxx_20
--> does Compile fine. 

with the Setting 14 it brings following Error: 

```
In file included from /home/franz/esp-idf-v5.1.1/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:76,
                 from /home/franz/esp-idf-v5.1.1/components/freertos/FreeRTOS-Kernel/include/freertos/portable.h:59,
                 from /home/franz/esp-idf-v5.1.1/components/freertos/FreeRTOS-Kernel/include/freertos/FreeRTOS.h:71,
                 from /home/franz/esp-idf-v5.1.1/components/driver/twai/include/driver/twai.h:9,
                 from /home/franz/git/ms/AgIsoStack-plus-plus-sample/sample/components/AgIsoStack-plus-plus/AgIsoStack-plus-plus/hardware_integration/include/isobus/hardware_integration/twai_plugin.hpp:17,
                 from /home/franz/git/ms/AgIsoStack-plus-plus-sample/sample/components/AgIsoStack-plus-plus/AgIsoStack-plus-plus/hardware_integration/src/twai_plugin.cpp:10:
/home/franz/esp-idf-v5.1.1/components/esp_common/include/esp_macros.h:87:25: error: static assertion failed: CHOOSE_MACRO_VA_ARG() result does not match for 0 arguments
   87 | ESP_STATIC_ASSERT(foo() == 2, "CHOOSE_MACRO_VA_ARG() result does not match for 0 arguments");
      |                         ^
/home/franz/esp-idf-v5.1.1/components/esp_common/include/esp_macros.h:87:25: note: the comparison reduces to '(1 == 2)'
```

The reason might be: 

`-std=gnu++2b -fno-exceptions -fno-rtti -std=c++14`
The command line then contains 2 non-compatible Cxx Standards. 

**Environment (please complete the following information):**
 - OS: [esp-idf-v5.1.1]
 - Compiler [xtensa-esp32-elf-g++ (crosstool-NG esp-12.2.0_20230208) 12.2.0]
 - CAN Driver [TWAI]

**Additional context**
Add any other context about the problem here that you think might help us recreate or otherwise address your issue if applicable.

**Comment by GwnDaan** [comment] 2023-11-25 10:39
Hi! I'm trying to reproduce this issue, would you be able to provide the full command used to build the project? In particular, where did you find `-std=gnu++2b -fno-exceptions -fno-rtti -std=c++14` arguments?

**Comment by GwnDaan** [comment] 2023-11-25 10:49
@franz-ms-muc I can confirm the build fails when running with the build argument `-std=c++14` for ESP-IDF. Try running the build command only with `-std=gnu++2b`, that works for me.

**Comment by franz-ms-muc** [comment] 2023-11-25 13:01
> @franz-ms-muc I can confirm the build fails when running with the build argument `-std=c++14` for ESP-IDF v5.1.1. Try running the build command only with `-std=gnu++2b`, that works for me.

where do you set these ?

**Comment by franz-ms-muc** [comment] 2023-11-25 13:03
> Hi! I'm trying to reproduce this issue, would you be able to provide the full command used to build the project? In particular, where did you find `-std=gnu++2b -fno-exceptions -fno-rtti -std=c++14` arguments?

you find it in the Output. for every Source File cmake outputs the Called Compiler line. 

[https://gist.github.com/franz-ms-muc/cef012699935ba0fa8be564821bfc212](https://gist.github.com/franz-ms-muc/cef012699935ba0fa8be564821bfc212)

see here for just this line.

**Comment by GwnDaan** [comment] 2023-11-25 13:22
I'm not 100% sure, i tested in PlatformIO, so it's was a little different there, but I think the following would work for you: 

In your own CMakeLists.txt edit the `CXX_STANDARD` variable, and making sure that is done _after_ AgIsoStack is added. So for example:

```cmake
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

or maybe unsetting it could work aswell:

```cmake
unset(CMAKE_CXX_STANDARD)
unset(CMAKE_CXX_STANDARD_REQUIRED)
```

In your case that probably would be at the very end of the agisostack 'component' CMakeLists.txt you configured, or somewhere in the CMakeLists.txt of your project itself. Let me know if that works :)

**Comment by GwnDaan** [comment] 2023-12-12 16:00
Hi @franz-ms-muc, your original issue should be fixed by https://github.com/Open-Agriculture/AgIsoStack-plus-plus/commit/f690bdda95222b72b6c95abfc7c0f91a2f23e74c. Any chance you would be able to test it with your initial setup?

**Comment by GwnDaan** [comment] 2024-01-30 20:10
Closing due to inactivity, feel free to re-open if issue still present

**Closed by GwnDaan** 2024-01-30 20:10 UTC
Labels: question, os: esp-idf
